version: '3.9'
services:

  node:
    build: ./nodejs
    container_name: node3
    ports: 
      - 80:8080
    #environment:
    #  - DB_URL="mysql db url" //todo enter DB connector
    volumes:
      - "C:/Users/Richard/OneDrive - University of Saskatchewan/CMPT 353/Assignments/Assignment 3/nodejs:/usr/src/app" #Desktop
      - "C:/Users/Richard/OneDrive - University of Saskatchewan/CMPT 353/Assignments/Assignment 3/mysql:/var/lib/mysql" #Desktop
      #- "C:/Users/Venom/OneDrive - University of Saskatchewan/CMPT 353/Assignments/Assignment 3/nodejs:/usr/src/app" #Laptop
      #- "C:/Users/Venom/OneDrive - University of Saskatchewan/CMPT 353/Assignments/Assignment 3/mysql:/var/lib/mysql" #Laptop
    #depends_on:
    #  mysql:
    #    condition: service_started
    stdin_open: true
    tty: true
  #mysql:
  #  image: mysql:5.7
  #  container_name: db1
  #  volumes:
  #    - "C:/Users/Richard/OneDrive - University of Saskatchewan/CMPT 353/Assignments/Assignment 3/mysql:/var/lib/mysql"
  #  environment:
  #    MYSQL_ROOT_PASSWORD: admin