services:
 couchdb:
  image: couchdb:3.4.2
  container_name: couchdb1
  restart: unless-stopped
  environment:
    - COUCHDB_USER=admin
    - COUCHDB_PASSWORD=password
  ports:
    - "5984:5984"
  volumes:
    - ./couchdb:/opt/couchdb/data
 node1:
  image: node:latest
  container_name: node1
  depends_on:
    - couchdb
  ports:
    - "8080:8080"
  environment:
    - COUCHDB_URL=http://admin:password@couchdb:5984
    - COUCHDB_DB=questionsdb
  volumes:
    - ./Backend:/backend
  working_dir: /backend  
  command: ["sh", "-c", "npm install --silent && node server.js"]
  stdin_open: true
  tty: true
 web:
  build: ./frontend
  container_name: react1
  ports:
   - "3000:3000"
  volumes:
   - ./frontend:/react-app
  stdin_open: true
  tty: true 
  command: ["npm", "start"]