FROM node:latest

EXPOSE 8080

#WORKDIR /Server

COPY package*.json ./

#RUN npm init -y
#RUN npm install
#RUN npm install express
#RUN npm install bodyParser
#RUN npm install -g loadtest

CMD ["node" "server.js"]