version: '3.9'
services:
  node:
    build: .
    container_name: node_yt
    ports: 
      - 80:8080
    volumes:
      - "C:/Users/Richard/OneDrive - University of Saskatchewan/CMPT 353/Assignments/assn3:/usr/src/app" #Desktop
      #- "C:/Users/Richard/OneDrive - University of Saskatchewan/CMPT 353/Assignments/Assignment 3/nodejs:/usr/src/app" #Desktop
      - "C:/Users/Richard/OneDrive - University of Saskatchewan/CMPT 353/Assignments/assn3/mysql:/var/lib/mysql" #Desktop
      #- "C:/Users/Venom/OneDrive - University of Saskatchewan/CMPT 353/Assignments/Assignment 3/nodejs:/usr/src/app" #Laptop
      #- "C:/Users/Venom/OneDrive - University of Saskatchewan/CMPT 353/Assignments/Assignment 3/mysql:/var/lib/mysql" #Laptop
      #- "C:/Users/Venom/OneDrive - University of Saskatchewan/CMPT 353/Assignments/Assignment 3/youtube traversy media:/usr/src/app" #Laptop
    depends_on:
      mysql:
        condition: service_started
    stdin_open: true
    tty: true
  mysql:
    image: mysql:5.7
    container_name: db1
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - "C:/Users/Richard/OneDrive - University of Saskatchewan/CMPT 353/Assignments/assn3/mysql:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: postdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: rootpw
      