version: "3.9"
services:
  node1:
    build: .
    container_name: nodeTut
    ports:
    - 82:8080
    volumes:
    - "C:/Users/venom/OneDrive - University of Saskatchewan/CMPT 353/Tutorials/week9/node:/Server"
    - "C:/Users/venom/OneDrive - University of Saskatchewan/CMPT 353/Tutorials/week9/Data:/Data"
  frontend:
    build: .
    container_name: reactTut
    ports:
    - 81:8081
    volumes:
    - "C:/Users/venom/OneDrive - University of Saskatchewan/CMPT 353/Tutorials/week9/react:/Server"
    - "C:/Users/venom/OneDrive - University of Saskatchewan/CMPT 353/Tutorials/week9/Data:/Data"
    stdin_open: true
    tty: true