services:
<<<<<<< HEAD
 a5cdb1:
  image: couchdb:3.4.2
  container_name: a5cdb1
=======
 couchdb:
  image: couchdb:3.4.2
  container_name: couchdb1
>>>>>>> origin/main
  restart: unless-stopped
  environment:
    - COUCHDB_USER=admin
    - COUCHDB_PASSWORD=password
  ports:
    - "5984:5984"
  volumes:
    - ./couchdb:/opt/couchdb/data
<<<<<<< HEAD
 a5n1:
  image: node:latest
  container_name: a5n1
  depends_on:
    - a5cdb1
  ports:
    - "80:3000"
  command: ["bin/bash"]  
  environment:
    - COUCHDB_URL=http://admin:password@a5cdb1:5984
    - COUCHDB_DB=postdb
    - COUCHDB_USER=admin
    - COUCHDB_PASSWORD=password
  volumes:
    - ./app:/usr/src/app
  working_dir: /usr/src/app
=======
 node1:
  image: node:latest
  container_name: node1
  depends_on:
    - couchdb
  ports:
    - "80:8080"
  command: ["bin/bash"]  
  environment:
    - COUCHDB_URL=http://admin:password@couchdb:5984
    - COUCHDB_DB=questionsdb
  volumes:
    - ./app:/usr/src/app
>>>>>>> origin/main
  stdin_open: true
  tty: true