services:
 couchdb:
  image: couchdb:3.4.2
  container_name: couchdb1
  restart: unless-stopped
  environment:
    - COUCHDB_USER=admin
    - COUCHDB_PASSWORD=password
  ports:
    - "5984:5984"
  volumes:
    - ./couchdb:/opt/couchdb/data
 node1:
  image: node:latest
  container_name: node1
  depends_on:
    - couchdb
  ports:
    - "80:8080"
  command: ["bin/bash"]  
  environment:
    - COUCHDB_URL=http://admin:password@couchdb:5984
    - COUCHDB_DB=questionsdb
  volumes:
    - ./app:/usr/src/app
  stdin_open: true
  tty: true