FROM node:latest

EXPOSE 3000

WORKDIR /usr/src/app

COPY ./package*.json /usr/src/app

#RUN npm init
RUN npm install
RUN npm install express
RUN npm install mysql
RUN npm install react
RUN npm install -g nodemon

CMD ["npm","run","--prefix","/project","start"]
