FROM node:latest

EXPOSE 8080

WORKDIR /usr/src/app

COPY ./package*.json /usr/src/app

#RUN npm init
RUN npm install
RUN npm install express
RUN npm install mysql
RUN npm install react

CMD ["/bin/bash"]
